---
Name: silverstripe-okta-config
---
SilverStripe\Security\Group:
  # default group to be used as parent
  okta_group:
    Code: 'okta-root'
    Title: 'Okta'
    Description: 'This is the parent group for all groups imported from Okta'
    IsOktaGroup: 1
    Locked: 1
---
Name: silverstripe-okta-support-assistance
---
NSWDPC\Authentication\Okta\AccessSupportAssistance:
  assistance_link: ''
