---
Name: silverstripe-okta-config
---
SilverStripe\Security\Group:
  # default group to be used as parent
  okta_group:
    Code: 'okta-root'
    Title: 'Okta'
    Description: 'Okta group'
    IsOktaGroup: 1
    Locked: 1
---
Name: silverstripe-okta-support-assistance
---
NSWDPC\Authentication\Okta\AccessSupportAssistance:
  assistance_link: ''
---
Name: silverstripe-okta-linker
---
NSWDPC\Authentication\Okta\OktaLinker:
  update_existing_member: true
